name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Godot Android Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_version: 4.2.1
          export_debug: true
          relative_project_path: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/
