name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Godot Android Export
        uses: chickensoft-games/godot-export@v1
        with:
          godot-version: 4.2.1
          platform: android
          export-type: debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: '**/*.apk'
